### ISSUE TITLE
Can not convert signal strength level '5' from HUAWEI CLT-L29

### ISSUE THREAD

**Issue by bakito** [frimtec/pikett-assist#59] opened 2019-10-15 15:51 UTC
I get the following error when the app is started.

Regards,
bakito (Marc)

Android version: 28
Device: HUAWEI CLT-L29
App version: 1693
Thread name: main

Exception stack trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.frimtec.android.pikettassist/com.github.frimtec.android.pikettassist.activity.MainActivity}: java.lang.IllegalArgumentException: Unknown level: 5
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.IllegalArgumentException: Unknown level: 5
at com.github.frimtec.android.pikettassist.helper.SignalStrengthHelper$SignalLevel.from(SignalStrengthHelper.java:73)
at com.github.frimtec.android.pikettassist.helper.SignalStrengthHelper$SignalLevel.access$000(SignalStrengthHelper.java:49)
at com.github.frimtec.android.pikettassist.helper.SignalStrengthHelper.getSignalStrength(SignalStrengthHelper.java:45)
at com.github.frimtec.android.pikettassist.activity.StateFragment.regularStates(StateFragment.java:301)
at com.github.frimtec.android.pikettassist.activity.StateFragment.createAdapter(StateFragment.java:194)
at com.github.frimtec.android.pikettassist.activity.AbstractListFragment.refresh(AbstractListFragment.java:51)
at com.github.frimtec.android.pikettassist.activity.AbstractListFragment.onCreateView(AbstractListFragment.java:42)
at android.app.Fragment.performCreateView(Fragment.java:2537)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1301)
at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2433)
at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2212)
at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2168)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2069)
at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3059)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3006)
at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
at android.app.Activity.performCreate(Activity.java:7465)
at android.app.Activity.performCreate(Activity.java:7448)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
... 11 more``

**Comment by bakito** [comment] 2019-10-15 15:55
When starting the app the app chooser icon is presented. Perhaps rhis is related to the error.
![Screenshot_20191015_174935](https://user-images.githubusercontent.com/2733215/66848182-e80e3200-ef74-11e9-92c1-c7a39ab9558f.jpg)

**Comment by bakito** [comment] 2019-10-15 16:00
Deleting the cache, data and reinstalling the app does not fix the problem

**Comment by bakito** [comment] 2019-10-15 16:03
Btw: i have a dual sim device. Since the error is in the signal strength code, this might cause the issue.

**Comment by frimtec** [comment] 2019-10-15 16:06
Hi Marc
The issue is that my code does not yet understand the signal level 5. 
I will fix that asap.

The other issue with the app chooser is most probably related to #58.

**Comment by frimtec** [comment] 2019-10-15 17:53
Fixed with 1.1.3-Bazooka.

**Closed by frimtec** 2019-10-15 17:53 UTC
Labels: bug
